final gitHubLink = "https://github.com/mariam280";
final myEmail = "mailto:neamamohammed649@gmail.com";
final myCV =
    "https://drive.google.com/file/d/1ff94LndRWyKu6Z9AmV3rOAiZQLx-jRDo/view?usp=sharing";
final linkdenLink = "https://www.linkedin.com/in/mariam-ebrahim-15605a348";
final newsifyGitHub = "https://github.com/mariam280/newsify_app";
final newsifyDemo =
    "https://drive.google.com/file/d/18La3lwhXM_cZlsspxU3JId-leJR3MbTt/view?usp=sharing";
final aiGitHub = "https://github.com/AmmarEmad-2004/Ai_chat";
final aiDemo =
    "https://drive.google.com/file/d/1pE9vF2331bBl5bEvT_UTHxADgyR9HHRa/view?usp=sharing";
final mtodoGitHub = "https://github.com/mariam280/mtodo_app";
final mtodoDemo =
    "https://drive.google.com/file/d/1pE9vF2331bBl5bEvT_UTHxADgyR9HHRa/view?usp=sharing";
